import React from 'react';
import './auditorium.css';

const Auditorium = () => {
  return (
    <div className="auditorium-container">
      <h1>University Auditorium</h1>
      <h2>General Zorawar Singh Auditorium:-</h2>
      <p>
      The General Zorawar Singh Auditorium is a State of Art auditorium. The Auditorium Complex is named after one of the most illustrious sons of Jammu, General Zorawar Singh. It was the then Chancellor of the University, Lt. Gen. (Retd.) S. K. Sinha, PVSM, who suggested the name. According to the family tradition, Zorawar was born in about 1784 AD in a Chandravanshi Kahluria family at the village of Ansar in tehsil Hamirpur of the Kangra district. As a youth, Zorawar Singh was a bold and intrepid adventurer who served as a soldier in the army of Maharaja Ranjit Singh and Maharaja Sansar Chand of Kangra. Later, he joined Maharaja Gulab Singh’s army and his valiant and chivalrous disposition caught the attention of Gulab Singh who appointed Zorawar as Inspector of Commissariat supplies for all the forts north of Jammu. When Kishtwar was annexed by Gulab Singh in 1820, Zorawar Singh was appointed as Hakim (Governor) of that district, a position he held upto 1836. The stage was set for Zorawar’s greatest military expedition. He prepared his army for combat in the lofty snow bound lands north of the Himalayas. Zorawar Singh’s conquest of Ladakh, Baltistan and Tibet is etched in golden words in the annals of high altitude warfare, and can be compared to Hannibal’s march across the Alps. 
      </p>
      <p>
      The Auditorium has a seating capacity of more than 1500. The auditorium can be divided into two parts: the main auditorium with a capacity of more than 1000, and a mini auditorium - with its own hydraulic stage, acoustic, sliding-folding partition - with a seating capacity of about 500. Two hi-tech elevators are an added convenience. The Art Gallery in the basement houses the Curator’s Room, the Miniature Gallery, a special lift for the physically challenged and a Freight Elevator for carriage of Heavy artifacts. The T.V. Studio in the second basement includes a Control Room, Rehearsal Room, Editing Room and a modern studio. The ground floor includes the Museum, a Souvenir shop, a Photo Gallery, the Curator's Room and the Cafeteria. On the ground floor, there is also a Special Complex with facilities like a Lounge Room, Dining Hall, and Pantry and with direct access to the stage. In addition, the ground floor also hosts a Conference Room, a Communication Room, Administration Office, Green Room (Ladies), Green Room (Gents), and the Administrator’s Room. The first Floor houses a Seminar Room, the FM Radio Station, Media Centre, Office and two Exhibition halls. The second Floor houses Offices, several brain-storming rooms and an Art Studio for children. The third Floor has Conference Rooms, a Reading room-cum-library while the Master Control Room is located on the fourth floor.
      </p>
      <img src="images/Auditorium01.jpg" alt="" />
      <img src="images/audi1.jpg" alt="" />
      <p>Jammu is the historic city but during these days its not only the City of Temples that is attracting the tourist but the newly constructed General Zorawar Singh Auditorium Complex with its vibrant backdrop has taken precedence and has managed to surpass every other square and place of interest in the city. It is attracting the people from the State as well as from national and international level.</p>
      <p>
      During the year 2003, the Hon’ble Prime Minister of India, during his visit to the state, released a special grant of Rs 30 crore to the University of Jammu and it was decided to use a part of it to construct a multipurpose Auditorium Complex. In addition, a special Auditorium Fund was created and resources were raised, including through generous donations from civil society. The foundation stone for the building was laid by the then Governor and then Chancellor of the University of Jammu.
      </p>
      <p>
      General Zorawar Singh Auditorium Complex is the name to be reckoned with even before its inauguration, it was well anticipated that General Zorawar Singh Auditorium Complex is going to be the hub of the activities. The inauguration of auditorium complex on 28th March, 2007 was in itself a event to which every one was looking forward.
      </p>
      <p>
      The Complex, with its unique Museum and Art Gallery, is a celebration of the symbiotic relationship of Jammu, Kashmir and Ladakh and showcases the rich cultural heritage and diversity of our State. The magnificent high-tech facility provides the perfect blend of creative, artistic and academic ambience to showcase the University of Jammu as a true centre of holistic education. The building is one of the first of its own kind in North India. Its uniqueness lies in the fact that this four storied state-of-the-art Auditorium Complex includes an Art Gallery, Photo Gallery, Exhibition Halls, Heritage Museum, Conference Halls, TV Studio, FM Radio Station, Media Centre, Art Studio for children and a Cafétéria with a Parisian ambience.
      </p>
      <p>
      Hon'ble Prime Minister of India, Dr. Manmohan Singh couldn.'t have been more specific while complimenting the university auditorium, when he said, "the place where I am standing is the true reflection of the heights Jammu University has reached." Former Chief of the Army Staff, General N.C Vij when visited the Auditorium Complex was so much taken by its beauty and style that he sufficed by saying that, "the University has done something inspirational by displaying the rare and forgotten." The Ex-Air Chief Marshal S. P. Tyagi was so overwhelmed with the architectural design that he pen downed following words, "I am impressed with the grand vision. Very happy to see the vision being translated to reality. This is an outstanding impressive place".
      </p>
      <img src="images/gal1_0.jpg" alt="" />
      <img src="images/inner.jpg" alt="" />
      <p>General Zorawar Singh Auditorium is the amalgamation of history, culture and contemporary art. It is indeed a tribute to the people of Jammu, Kashmir and Ladakh. It is a matter of pride privilege and pleasure to be the part of this Auditorium Complex. which promises a rich offering of art and modern technology.</p>
      <p>The Art Gallery is named after Lotsava Rinchen Bzangpo (c. 958-1055 A.D.), a great Scholar and Translator, who was responsible for the foundation of 108 monasteries (Gompas) throughout Ladakh, Western Tibet and Lahul Spiti (Himachal Pradesh). He played a very important role in laying a firm foundation for Buddhism in Ladakh region and is known as the 'Father of Buddhist Culture in Ladakh'. The monasteries (Gompas) built by Rinchen Bzangpo are renowned for their architecture, which includes rich wood carvings and fine wall paintings. The idea of dedicating this gallery to Lotsava Rinchen Bzangpo is to propagate his vision towards the Arts. Hence the purpose of the Gallery is preservation, dissemination and research, which makes it distinct from other art galleries of the country. The major collection of the Gallery is of contemporary paintings. These have been received from the artists who participated in the "All India Contemporary Artists Camp" at Patnitop (Jammu) in October 2004, organised by the University of Jammu. The other collection is black & white photographs, sketches and paintings which have been donated by renowned artists and art historians like Prof. S.D.S Charak, Satti Sahni and Serbjeet Singh. The Art Gallery also houses some beautiful wooden sculptures, which were carved in the special "Wood Carving Camp" organised by the University of Jammu in 2005 and attended by renowned sculptors from all over the country. The Rinchen Bzangpo Art Gallery is divided into six different sections according to their theme and artists viz; Contemporary Paintings, Panorama and Sketches of Serbjeet Singh, Wall Paintings of Jammu Region, Scroll Paintings (Thangkas), Pahari Miniature Paintings and Satti Sahni Gallery of Photographs</p>
      <p>
      The Heritage Museum is named in honour of the great Sufi saint Sheikh Nur-Ud-Din Noorani (1378-1439 AD), popularly known as Nund Rishi. He was the propagator of Rishi cult and devoted his life for the cause of humanity. He derived inspiration from the holy Quran and gave a distinct Kashmiri tinge to Islamic doctrines. He propagated the philosophy of 'Unity of Being' and non-violence. Sheikh Nur-ud-Din died in 1439 and was buried with royal pomp at the village of Chrar. The highlights of the Museum are the display of different categories of artifacts in a continuous sequence covering the entire history and culture from pre-historic times to contemporary. The pre-historic section displays tools from the sites of Malpur (Jammu) and Burzahom (Kashmir). Some examples of pre-historic rock petroglyphs of Ladakh are exhibited in a re-constructed form. Replica of Burzahom pit presents the unique Neolithic culture of Kashmir. The Historic period of Jammu is represented by the artifacts belonging to the Kushana and the Gupta periods excavated from the two sites-Manda and Ambaran (Akhnoor). The remains of Krimchi temple are recreated to show the temple tradition of 7th and 8th century AD.
      </p>
      <h2>Brigadier Rajinder Singh Auditorium:- </h2>
      <p>Brigadier Rajinder Singh Auditorium has a seating capacity of  250 persons and is remains in great demands for hosting national seminars and conferences. It is one of the venue of "Display your Talent", a programme of the student to perform and to show their talents in the literary and the cultural activities.</p>
      <img src="images/smallAuditorium.jpg" alt="" />
      <img src="images/sideAudi_Inside.jpg" alt="" />
      <p>Besides to these two major auditoriums, the University of Jammu has one small auditorium in the Department of Computer Sciences & IT. It has a seating capacity of 200 persons. Another small auditorium is in the Business School, University of Jammu.</p>
    </div>
  );
};

export default Auditorium;
